        </div>
        <div id="footer">
            <small>&copy; <?= date( 'Y' ); ?> <a href="http://ajmm.org/">Andrew Mackrodt</a></small>
        </div>
    </div>
</div>
<script src="<?= asset_url( 'js/jquery.3.4.1.js' ); ?>"></script>
<script src="<?= asset_url( 'js/jquery.placeholder.js' ); ?>"></script>
<script src="<?= asset_url( 'js/bootstrap.js' ); ?>"></script>
<script src="<?= asset_url( 'js/jquery.switch.js' ); ?>"></script>
<script src="<?= asset_url( 'js/swfobject.js' ); ?>"></script>
<script src="<?= asset_url( 'js/downloadify.js' ); ?>"></script>
<script src="<?= asset_url( 'js/functions.js' ); ?>"></script>
</body>
</html>