<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>PHPMD Ruleset Builder</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Andrew Mackrodt" />
    <link href="<?= asset_url( 'css/bootstrap.css' ); ?>" rel="stylesheet" />
    <link href="<?= asset_url( 'css/bootstrap-responsive.css' ); ?>" rel="stylesheet" />
    <link href="<?= asset_url( 'css/bootstrap-switch.css' ); ?>" rel="stylesheet" />
    <link href="<?= asset_url( 'css/style.css' ); ?>" rel="stylesheet" />
    <script>BASE_URL = '<?= BASE_URL; ?>';</script>
</head>
<body data-spy="scroll" data-target="#navbar-container">
<div class="container">
    <div class="row">
        <div id="navbar-container" class="span3">
            <ul id="navbar" class="nav nav-list affix">
            <?php foreach ( get_navbar_contents() as $id => $name ): ?>
                <li>
                    <a href="#<?= $id; ?>"><i class="icon-chevron-right"></i> <?= $name; ?></a>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
        <div class="span9">
            <div id="github">
                <img src="<?= asset_url( 'img/github.png' ); ?>" alt="" width="16px" height="16px" />
                <small>
                    <a href="https://github.com/andrewmackrodt/phpmd-ruleset-builder" target="_blank">Fork me on GitHub</a>
                </small>
            </div>
            <h1>PHPMD Ruleset Builder</h1>
