        </div>
        <div id="footer">
            <small>&copy; <?= date( 'Y' ); ?> <a href="http://ajmm.org/">Andrew Mackrodt</a></small>
        </div>
    </div>
</div>
<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/jquery.switch.js"></script>
<script src="assets/js/jquery.placeholder.min.js"></script>
<script src="assets/js/functions.js"></script>
</body>
</html>