<div>
    <p>A tool to quickly create PHPMD rulesets.</p>
    <p>PHPMD analyzes a PHP project for potential problems within its code. These include:</p>
    <ul>
        <li>Possible bugs</li>
        <li>Suboptimal code</li>
        <li>Overcomplicated expressions</li>
        <li>Unused parameters, methods and properties</li>
    </ul>
    <p><a href="http://phpmd.org/" target="_blank">Find out more</a></p>
</div>

<form class="form-horizontal">
    <fieldset id="basicsettings">
        <legend>Basic Settings</legend>
        <div class="control-group">
            <div class="control-label">
                <label><strong>Name</strong></label>
            </div>
            <div class="controls">
                <input class="span3" type="text" name="name" placeholder="The name of the ruleset">
            </div>
        </div>
        <div class="control-group">
            <div class="control-label">
                <label><strong>Description</strong></label>
            </div>
            <div class="controls">
                <textarea class="span5" name="description" placeholder="A short description describing the ruleset"></textarea>
            </div>
        </div>
        <div class="control-group">
            <div class="control-label">
                <div class="switch switch-medium">
                    <input name="advanced" type="checkbox" />
                </div>
            </div>
            <div class="controls">
                <p>
                    <strong>Advanced Settings</strong>
                    Allows changing the reporting priority and configurable options of rules.
                </p>
            </div>
        </div>
    </fieldset>

    <? foreach ( get_rulesets() as $filename => $ruleset ): ?>
        <? $id = substr( $filename, 0, -4 ); ?>
        <? $navbar[$id] = $ruleset['name']; ?>
        <fieldset id="<?= $id; ?>" class="ruleset">
            <legend><?= $ruleset['name']; ?></legend>
            <p><?= $ruleset['description']; ?></p>
            <? foreach ( $ruleset['rules'] as $rule ): ?>
                <div class="control-group rule">
                    <div class="control-label">
                        <div class="switch switch-medium">
                            <input name="<?= $rule['id']; ?>[enabled]" type="checkbox" checked="checked" />
                        </div>
                    </div>
                    <div class="controls">
                        <div>
                            <p>
                                <strong><?= $rule['name']; ?></strong>
                                <?= $rule['description']; ?>
                            </p>
                        </div>
                        <fieldset class="options">
                            <div class="control-group priority">
                                <select name="<?= $rule['id']; ?>[priority]" data-default="<?= $rule['priority']; ?>">
                                    <? foreach( array( 'highest', 'high', 'normal', 'low', 'lowest' ) as $v => $k ): ?>
                                        <? $selected = ++$v == $rule['priority'] ? ' selected="selected"' : ''; ?>
                                        <option value="<?= $v; ?>"<?= $selected; ?>><?= $k; ?></option>
                                    <? endforeach; ?>
                                </select>
                            </div>
                            <? foreach ( $rule['properties'] as $name => $property ): ?>
                                <div class="control-group property">
                                    <p>
                                        <strong><?= $property['name']; ?></strong>
                                        <?= $property['description']; ?>
                                    </p>
                                    <input name="<?= "{$rule['id']}[$name]"; ?>" placeholder="<?= $property['value']; ?>" type="text" />
                                </div>
                            <? endforeach; ?>
                        </fieldset>
                    </div>
                </div>
            <? endforeach; ?>
        </fieldset>
    <? endforeach; ?>
</form>

<fieldset id="phpmd">
    <legend>PHPMD Ruleset</legend>
    <a href="#" class="btn btn-link downloadify" id="save">Save phpmd.xml</a>
    <pre></pre>
</fieldset>
